### ISSUE TITLE
set recolor "false"

### ISSUE THREAD

**Issue by AxelBohm** [HaoZeke/base16-zathura#1]
First of all thank you for this repo.
Second, why would you set recolor default to "false" ? it took me a couple of minutes to figure out why the colorscheme was not working after copy and pasting the code into my rc file..

**Comment by nicodebo** [comment]
Hi,
In my opinion, recolor "true" is a very opinionated setting. That's why I decided to set it to "false" and keep it in the theme so that users can change it. Maybe I could add a note in the Readme (stating that recolor is set to false) or make a second template with recolor set to "true". What do you think ?

**Comment by AxelBohm** [comment]
as far as i understood setting recolor to "true" is necessary for the colorscheme take effect? it's not clear to me why anyone would copy the colorscheme and then not set it to true.. but i guess one additional line in the Readme will do just fine.

**Comment by nicodebo** [comment]
The recolor option only affect the look of the document. Even if recolor is set to false, the UI (status bar, input bar, background color, ...) still follows the colorscheme.

**Comment by dylnmc** [comment]
a fair bit of people that use zathura use tiling window managers .. I agree with "I copied a colorscheme so that the colorscheme would act like a colorscheme." You can just press <kbd>ctrl</kbd><kbd>r</kbd> to toggle `recolor`

**Comment by Qu4tro** [comment]
Hello there. I'm in the opinion that we shouldn't set recolor at all.

The default option on zathura is `recolor=false`, so in effect, the template is redudant, apart from a single, fairly relevant case: 

When we `include` the colorscheme on `zathurarc` (assuming multiple files), it needs to be included *before* your custom 'recolor'.
On the other hand if we include it afterwards (i.e. bottom of config), it overwrites user-defined configuration.

My suggestion is to remove the opinion altogether from the template and remove the `recolor` settings.

Only possible issue, I can think of is that we would be relying on Zathura defaults, which might change over time. 
Personally, I think that it's a pretty sane thing to do, in this case.

Cheers

**Comment by nicodebo** [comment]
hi,
maybe I should add a second template with set recolor=True to this repository so that both options are available. (and remove the recolor option from the current one as you mentioned)

**Comment by Qu4tro** [comment]
Yeah, no problem. Will add a PR.
