### ISSUE TITLE
some more zathura themes

### ISSUE THREAD

**Issue by bakageddy** [HaoZeke/base16-zathura#5]
I have made some ports to popular colorschemes:
[iceberg](https://github.com/gdnand/zathura-iceberg)
[embark-theme](https://github.com/gdnand/zathura-embark-theme)
[moonfly](https://github.com/gdnand/zathura-moonfly)

I have modified this existing nord config to make it look better:
[nord](https://github.com/gdnand/zathura-nord)

**Comment by HaoZeke** [comment]
Hi @gdnand , sorry for the late response. If these are base16 compliant would you like to make a PR to add them?
